### ISSUE TITLE
deprecated rand.Seed()

### ISSUE THREAD

**Issue by 8ugr4** [dmachard/go-dnstap-generator#37]
``rand.Seed()`` is deprecated, can ``rand.New(rand.NewSource(time.Now().UnixNano()))`` be used instead.

https://pkg.go.dev/math/rand#Seed

**Comment by dmachard** [comment]
Feel free to make a pull request :)

**Comment by 8ugr4** [comment]
Thanks. Just did one.

**Comment by dmachard** [comment]
Thanks. It's merged
